# Generated by Django 6.0.3 on 2026-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='columnas_categoricas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoanalisis',
            name='columnas_fecha',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoanalisis',
            name='columnas_numericas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
