# Generated by Django 6.0.3 on 2026-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_resultadoanalisis_columnas_categoricas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='insights',
            field=models.TextField(blank=True),
        ),
    ]
