# Generated by Django 6.0.3 on 2026-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_resultadoanalisis_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='preview_datos',
            field=models.TextField(blank=True),
        ),
    ]
