# Generated by Django 6.0.3 on 2026-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_resultadoanalisis_preview_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='datos_graficos',
            field=models.TextField(blank=True),
        ),
    ]
