# Generated by Django 6.0.3 on 2026-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_resultadoanalisis_datos_graficos'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='resumen_ia',
            field=models.TextField(blank=True),
        ),
    ]
