# Generated by Django 6.0.3 on 2026-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0007_dashboardguardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoanalisis',
            name='crecimiento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoanalisis',
            name='total_ordenes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadoanalisis',
            name='total_ventas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardguardado',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='columnas_categoricas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='columnas_fecha',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='columnas_numericas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='total_columnas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoanalisis',
            name='total_registros',
            field=models.IntegerField(default=0),
        ),
    ]
